# Generated by Django 3.2.5 on 2024-02-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_medic', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default='0000000000', max_length=10),
        ),
    ]
